### ISSUE TITLE
有一个疑惑点如果看到的话希望可以解决

### ISSUE THREAD

**Issue by duoluodexiaoxiaoyuan** [2462870727/personalBlog#1]
Next不是本身就是可以用来写后端吗？难道他只是简单的进行ssr渲染吗，写后端还是需要express,koa这样的框架

**Comment by jiangkaifree** [comment]
应该也是可以的， 但我没有尝试过




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jiangkaifree/personalBlog"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月10日(星期五) 下午4:15
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[jiangkaifree/personalBlog] 有一个疑惑点如果看到的话希望可以解决 (Issue #1)





 
Next不是本身就是可以用来写后端吗？难道他只是简单的进行ssr渲染吗，写后端还是需要express,koa这样的框架

**Comment by duoluodexiaoxiaoyuan** [comment]
没想到大佬回复的这么快，因为我看到好几篇都用到next但是他们只是它将前端页面ssr渲染，所以我很好奇。

**Comment by jiangkaifree** [comment]
在moyu&nbsp;【NextJS】创建后端 API 接口_哔哩哔哩_bilibili




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jiangkaifree/personalBlog"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月10日(星期五) 下午4:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jiangkaifree/personalBlog] 有一个疑惑点如果看到的话希望可以解决 (Issue #1)





 
没想到大佬回复的这么快，因为我看到好几篇都用到next但是他们只是它将前端页面ssr渲染，所以我很好奇。
