### ISSUE TITLE
想和大佬一起做项目

### ISSUE THREAD

**Issue by duoluodexiaoxiaoyuan** [2462870727/personalBlog#2]
看了大佬的github,感觉写的特别好，然后我也基本属于看得懂的项目。不知道大佬这个博客项目自用了吗？还是已经停滞了，不打算写了。
这是我的vx:woyaobaofuniubi   希望交个朋友

**Comment by jiangkaifree** [comment]
> 

哈哈哈哈，我真不是啥大佬，这是以前写的小项目，为了看看整个的一个前后端开发流程。现在不更新,维护起来成本比较高，工作忙。在[这里blog](https://jiangkaifree.github.io/study/#/) ，利用 文档工具更新了自己的一些东西。维护起来方便。但也好久没写了。

**Comment by jiangkaifree** [comment]
> 看了大佬的github,感觉写的特别好，然后我也基本属于看得懂的项目。不知道大佬这个博客项目自用了吗？还是已经停滞了，不打算写了。 这是我的vx:woyaobaofuniubi 希望交个朋友

哈哈哈哈，我真不是啥大佬，这是以前写的小项目，为了看看整个的一个前后端开发流程。现在不更新,维护起来成本比较高，工作忙。在[这里blog](https://jiangkaifree.github.io/study/#/) ，利用 文档工具更新了自己的一些东西。维护起来方便。但也好久没写了。

**Comment by duoluodexiaoxiaoyuan** [comment]
我看了发现了错误还提了pr，写的很好

**Comment by jiangkaifree** [comment]
> 

一般一般 写的很菜， 可以看看其他项目

**Comment by jiangkaifree** [comment]
> 我看了发现了错误还提了pr，写的很好

一般一般 写的很菜， 可以看看其他项目
